# Generated by Django 3.0.3 on 2020-02-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200227_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
